spring:
  profiles:
    active:
      - rds
  application:
    name: demo-mall

springdoc:
  swagger-ui:
    path: /swagger-ui.html

mybatis:
  mapper-locations:
    - classpath:mapper/*.xml
    - classpath*:com/**/mapper/*xml