server:
  port: 8081
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/mall?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Bangkok
    username: root
    password: 123456

logging:
  level:
    root: info
    com.ph.mall: debug



