spring:
  profiles:
    active:
      - rds
  application:
    name: admin-mall

springdoc:
  swagger-ui:
    path: /swagger-ui.html

mybatis:
  mapper-locations:
    - classpath:mapper/*.xml
    - classpath*:com/**/mapper/*xml
  configuration:
    map-underscore-to-camel-case: true
